<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\TradingScanner.Core\TradingScanner.Core.csproj" />
    <ProjectReference Include="..\TradingScanner.MarketData\TradingScanner.MarketData.csproj" />
    <ProjectReference Include="..\TradingScanner.Analytics\TradingScanner.Analytics.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
