import { Brand, ExampleChart, Icon, Sparkline, StatusPill } from "./Primitives";
export function Landing() {
  return <div className="sw sw-landing">
    <a className="sw-skip" href="#main">Skip to content</a>
    <header className="sw-site-header sw-container"><Brand /><nav aria-label="Main"><a href="#how-it-works">How it works</a><a href="#pricing">Pricing</a><a href="/legal#risk">Our approach</a></nav><div className="sw-header-actions"><a className="sw-text-link" href="/app?auth=login">Log in</a><a className="sw-button primary small" href="/app">Open free preview <Icon name="arrow" size={16} /></a></div></header>
    <main id="main">
      <section className="sw-hero sw-container">
        <div className="sw-hero-copy"><div className="sw-kicker"><span className="sw-live-dot" /> LESS SCREEN TIME. MORE PERSPECTIVE.</div><h1>Stay in the loop.<br /><span>Not on the chart.</span></h1><p className="sw-hero-description">Monitor crypto markets without staring at charts all day. A quieter way to find context, follow the coins you care about, and know when to take a closer look.</p><div className="sw-hero-actions"><a className="sw-button primary" href="/app">Explore the free preview <Icon name="arrow" size={18} /></a><a className="sw-button ghost" href="#how-it-works">See how it works</a></div><p className="sw-microcopy"><Icon name="check" size={14} /> No card required <span>·</span> Monitoring only. You stay in control.</p></div>
        <div className="sw-hero-orbit" aria-hidden="true"><div /><div /><div /><span className="sw-orbit-point one" /><span className="sw-orbit-point two" /><span className="sw-orbit-point three" /><div className="sw-orbit-core"><Icon name="waves" size={45} /></div></div>
      </section>
      <section className="sw-product-window sw-container" aria-label="Product illustration">
        <div className="sw-window-top"><div className="sw-window-dots"><i /><i /><i /></div><span>YOUR MARKET, AT A GLANCE</span><StatusPill>Illustrative product preview</StatusPill></div>
        <div className="sw-window-body"><aside className="sw-preview-nav"><Brand compact />{[{name:"home",label:"Home"},{name:"scan",label:"Scanner"},{name:"watch",label:"Watchlist"},{name:"alerts",label:"Alerts"}].map((n,i) => <span className={i === 0 ? "selected" : ""} key={n.name}><Icon name={n.name} size={18} />{n.label}</span>)}<span className="bottom"><Icon name="account" size={18} />Account</span></aside><div className="sw-preview-main"><div className="sw-section-heading"><div><span className="sw-label">YOUR DAILY PERSPECTIVE</span><h2>The market keeps moving.<br />You don’t have to.</h2></div><span className="sw-pill green">Example only</span></div><div className="sw-preview-grid"><div className="sw-preview-chart-card"><div className="sw-card-heading"><div className="sw-coin-row"><span className="sw-coin btc">₿</span><div><strong>Bitcoin</strong><span>BTC / USD · Example analysis</span></div></div><div className="sw-chart-price"><strong>$67,240.00</strong><span>Illustrative price</span></div></div><ExampleChart /><div className="sw-chart-caption"><Icon name="info" size={15} /> A conditional setup, with the context behind it.</div></div><div className="sw-preview-side"><div className="sw-mini-alert"><span className="sw-mini-alert-icon"><Icon name="alerts" /></span><span className="sw-label">AN ALERT WITH CONTEXT</span><h3>Bitcoin is testing a key level.</h3><p>Volume is rising near resistance. Wait for confirmation before reassessing.</p><div><StatusPill tone="amber">Conditional setup</StatusPill></div><span className="sw-caption">Illustrative example · not a trade recommendation</span></div><div className="sw-preview-watch"><span className="sw-label">ON YOUR RADAR</span>{[{symbol:"ETH",name:"Ethereum",variant:1},{symbol:"SOL",name:"Solana",variant:2}].map(c=><div key={c.symbol}><span className={`sw-coin ${c.symbol.toLowerCase()}`}>{c.symbol === "ETH" ? "Ξ" : "≋"}</span><span><strong>{c.name}</strong><small>{c.symbol} / USD</small></span><Sparkline variant={c.variant} muted={c.variant === 2} /></div>)}</div></div></div></div></div>
      </section>
      <div className="sw-principles sw-container"><span><Icon name="shield" /> No trading access needed</span><span><Icon name="clock" /> Freshness checks built in</span><span><Icon name="info" /> Context over predictions</span></div>
      <section className="sw-how sw-container" id="how-it-works"><div className="sw-section-intro"><span className="sw-kicker">A MORE CONSIDERED APPROACH</span><h2>Less noise.<br /><span>More of what matters.</span></h2><p>Make monitoring fit your day. Stillwatch keeps the details together, so you can decide what deserves your attention.</p></div><div className="sw-feature-grid">{[{n:"01",icon:"watch",title:"Make it your market.",text:"Choose a supported exchange, the coins you follow, and the market conditions you want to monitor."},{n:"02",icon:"scan",title:"Understand the setup.",text:"See what changed, why it matched, and what would invalidate it. Clear price levels, freshness, and estimated costs."},{n:"03",icon:"alerts",title:"Step away with context.",text:"Pro alerts run on the server. Set cooldowns and quiet hours, and receive push notifications on supported devices."}].map(f=><article key={f.n}><div><span>{f.n}</span><Icon name={f.icon} size={24} /></div><h3>{f.title}</h3><p>{f.text}</p></article>)}</div></section>
      <section className="sw-trust-band sw-container"><div><Icon name="shield" size={26} /><h3>Clarity is the product.<br />Certainty isn’t the promise.</h3></div><p>Scores describe heuristic conditions, not the odds of winning. Markets are risky, setups can fail, and push delivery can be delayed. Stillwatch helps you observe; every decision stays yours.</p><a href="/legal#risk" className="sw-text-link">Read our risk disclosure <Icon name="arrow" size={17} /></a></section>
      <section id="pricing" className="sw-pricing sw-container"><div className="sw-section-intro"><span className="sw-kicker">ROOM TO FIND YOUR RHYTHM</span><h2>Start curious.<br /><span>Go deeper when you’re ready.</span></h2><p>Explore the experience for free. Pro brings your market, your rules, and your alerts together.</p></div><div className="sw-price-grid"><article className="sw-price-card"><div className="sw-price-head"><h3>Free</h3><StatusPill>Get your bearings</StatusPill></div><div className="sw-price">$0<span>/ forever</span></div><p>A useful first look at a more focused way to monitor.</p><a href="/app" className="sw-button secondary">Explore free <Icon name="arrow" size={18} /></a><ul>{["Limited market overview when data is available","Clearly labeled example analyses","Save your starting preferences and 5 coins","Preview the complete workspace"].map(t=><li key={t}><Icon name="check" size={17} />{t}</li>)}</ul></article><article className="sw-price-card pro"><div className="sw-price-head"><h3>Pro</h3><span className="sw-pill green">Your monitoring companion</span></div><div className="sw-price">$29<span>/ month</span></div><p>Your watchlist. Your conditions. More time away.</p><a href="/app?tab=account" className="sw-button primary">Explore Pro <Icon name="arrow" size={18} /></a><ul>{["Full scanner and detailed setup explanations","Custom watchlists and alert rules","Background push on supported devices","Saved alert history and delivery diagnostics","Quiet hours and personal fee assumptions"].map(t=><li key={t}><Icon name="check" size={17} />{t}</li>)}</ul><div className="sw-pricing-note">Development preview · Checkout is test mode only. Paid public launch is pending commercial review.</div></article></div></section>
      <section className="sw-last-cta sw-container"><span className="sw-kicker">A LITTLE MORE ROOM IN YOUR DAY</span><h2>Keep an eye on the market.<br /><span>Get back to everything else.</span></h2><a href="/app" className="sw-button primary">Take a look inside <Icon name="arrow" size={18} /></a></section>
    </main><footer className="sw-site-footer sw-container"><div><Brand /><p>Thoughtful crypto market monitoring.</p></div><nav aria-label="Footer"><a href="/legal#privacy">Privacy draft</a><a href="/legal#terms">Terms draft</a><a href="/legal#risk">Risk disclosure</a><a href="/app?tab=account">Support</a></nav><p className="sw-footer-note">Development preview. No custody, automated trading, or investment advice. Public listings do not confirm availability in your exchange account.</p></footer>
  </div>;
}
