"use client";
import { useCallback, useEffect, useMemo, useRef, useState, type FormEvent } from "react";
import { productRequest, type Overview, type ProductMe, type ProductAlertEvent } from "@/lib/product-api";
import type { Opportunity, ScannerRow, ScannerStream } from "@/lib/types";
import { Brand, displaySymbol, EmptyState, ExampleChart, Icon, money, StatusPill, timeAgo } from "./Primitives";
import { Auth, type AuthMode } from "./Auth";
import { Account } from "./Account";
import { Alerts } from "./Alerts";
import { Setup } from "./Setup";
import { normalizeMarketSymbol, qualifies, snapshotIsFresh } from "@/lib/product-model";

type Tab = "home" | "scanner" | "watchlist" | "alerts" | "account";
const navigation: { tab: Tab; icon: string; label: string }[] = [{tab:"home",icon:"home",label:"Home"},{tab:"scanner",icon:"scan",label:"Scanner"},{tab:"watchlist",icon:"watch",label:"Watchlist"},{tab:"alerts",icon:"alerts",label:"Alerts"},{tab:"account",icon:"account",label:"Account"}];
const headings: Record<Tab, {eyebrow:string;title:string;description:string}> = { home:{eyebrow:"YOUR DAILY PERSPECTIVE",title:"A little context. A clearer day.",description:"Your market, your watchlist, and what deserves a closer look."}, scanner:{eyebrow:"FIND YOUR FOCUS",title:"The market, with context.",description:"Observe the conditions. Understand the setup. Make your own call."}, watchlist:{eyebrow:"MAKE IT YOUR MARKET",title:"Keep your coins close.",description:"A focused view of the markets you choose to follow."}, alerts:{eyebrow:"LESS WATCHING. MORE LIVING.",title:"Let the market come to you.",description:"Considered rules, useful context, and a transparent record."}, account:{eyebrow:"YOUR STILLWATCH",title:"Built around your day.",description:"Your membership, monitoring preferences, and a little peace of mind."} };

export function ProductApp() {
  const accountRequest=useRef(0);
  const [tab,setTab]=useState<Tab>("home"), [me,setMe]=useState<ProductMe|null>(null), [overview,setOverview]=useState<Overview|null>(null), [scanner,setScanner]=useState<ScannerStream|null>(null), [recent,setRecent]=useState<ProductAlertEvent[]>([]);
  const [loading,setLoading]=useState(true), [refreshing,setRefreshing]=useState(false), [error,setError]=useState(""), [scannerError,setScannerError]=useState(""), [sessionError,setSessionError]=useState(""), [online,setOnline]=useState(true), [tick,setTick]=useState(0);
  const [auth,setAuth]=useState<AuthMode|null>(null), [query,setQuery]=useState(""), [filter,setFilter]=useState("all"), [notice,setNotice]=useState(""), [savingWatch,setSavingWatch]=useState(false);
  const [detail,setDetail]=useState<{open:boolean; example:boolean;recorded:boolean;opportunity:Opportunity|null;loading:boolean;error:string}>({open:false,example:false,recorded:false,opportunity:null,loading:false,error:""});
  const navigate=useCallback((next:Tab)=>{ setTab(next); const params=new URLSearchParams(window.location.search); params.set("tab",next); params.delete("auth"); window.history.replaceState(null,"",`/app/?${params}`); window.scrollTo({top:0,behavior:"instant"}); },[]);
  const notify=useCallback((message:string)=>setNotice(message),[]);
  const closeAuth=useCallback(()=>{ setAuth(null); const params=new URLSearchParams(window.location.search); ["auth","action","email","token","userId"].forEach(k=>params.delete(k)); window.history.replaceState(null,"",`/app/?${params}`); },[]);
  const closeDetail=useCallback(()=>setDetail(d=>({...d,open:false})),[]);
  const refreshMe=useCallback(async()=>{ const request=++accountRequest.current; try { const result=await productRequest<ProductMe>("/me"); if(request!==accountRequest.current)return; setMe(result); setSessionError(""); } catch(e) { if(request!==accountRequest.current)return; setMe(null); setSessionError(e instanceof Error ? e.message : "Account services are unavailable."); } },[]);
  const refreshOverview=useCallback(async()=>{ setRefreshing(true); try { const result=await productRequest<Overview>("/overview"); setOverview(result); setError("");  } catch(e) { setError(e instanceof Error ? e.message : "The market service is unavailable."); } finally { setLoading(false); setRefreshing(false); } },[]);
  useEffect(()=>{
    const params=new URLSearchParams(window.location.search); const next=params.get("tab"); if(navigation.some(n=>n.tab===next)) setTab(next as Tab);
    const mode=params.get("auth")??params.get("action"); if(["login","register","forgot-password","reset-password","confirm-email"].includes(mode??"")) setAuth(mode as AuthMode);
    if(params.get("checkout")) setNotice("Back from checkout. Subscription access updates only after the server verifies the payment provider webhook.");
    void refreshMe(); void refreshOverview();
    const timer=setInterval(()=>{void refreshOverview();void refreshMe();},15000);
    const clock=setInterval(()=>setTick(x=>x+1),1000);
    const connected=()=>setOnline(navigator.onLine); connected(); window.addEventListener("online",connected); window.addEventListener("offline",connected);
    if("serviceWorker" in navigator && window.isSecureContext) void navigator.serviceWorker.register("/sw.js",{scope:"/"}).catch(()=>{});
    return ()=>{clearInterval(timer);clearInterval(clock);window.removeEventListener("online",connected);window.removeEventListener("offline",connected);};
  },[refreshMe,refreshOverview]);
  useEffect(()=>{ if(!notice) return; const timer=setTimeout(()=>setNotice(""),8000);return()=>clearTimeout(timer); },[notice]);
  useEffect(()=>{
    if(!me?.entitlements.scanner) {setScanner(null);setRecent([]);setScannerError("");return;}
    let cancelled=false;
    const load=async()=>{const result=await Promise.allSettled([productRequest<ScannerStream>("/scanner"),productRequest<ProductAlertEvent[]>("/alerts/history")]);if(cancelled)return;if(result[0].status==="fulfilled") {setScanner(result[0].value);setScannerError("");} else setScannerError(result[0].reason instanceof Error ? result[0].reason.message : "Scanner unavailable.");if(result[1].status==="fulfilled") setRecent(result[1].value.slice(0,3));};
    void load();const timer=setInterval(()=>void load(),15000);return()=>{cancelled=true;clearInterval(timer);};
  },[me?.entitlements.scanner,me?.user?.id]);
  const dataAt=scanner?.at??overview?.at;
  const stale=!!dataAt && !snapshotIsFresh(dataAt);
  const rows=(scanner?.rows??overview?.rows??[]).map(row=>({...row,stale:row.stale||stale||!online}));
  const qualifying=rows.filter(qualifies);
  const isLive=overview?.mode==="live" && overview.feed.live && online && !error && !scannerError && !stale;
  const filtered=useMemo(()=>rows.filter(row=>row.symbol.toLowerCase().includes(query.toLowerCase()) && (filter==="all" || filter==="fresh" && !row.stale || filter==="watching" && me?.watchlist.includes(row.symbol) || row.setup.toLowerCase().includes(filter))),[rows,query,filter,me?.watchlist,tick]);
  async function openSetup(symbol:string) {setDetail({open:true,example:false,recorded:false,opportunity:null,loading:true,error:""});try {const result=await productRequest<Opportunity>(`/setup/${encodeURIComponent(symbol)}`);setDetail(d=>({...d,opportunity:result,loading:false}));}catch(e){setDetail(d=>({...d,loading:false,error:e instanceof Error ? e.message : "Could not load this setup."}));}}
  function openExample(){setDetail({open:true,example:true,recorded:false,opportunity:null,loading:false,error:""});}
  function upgrade(){navigate("account");}
  async function saveWatch(symbols:string[]){if(!me?.authenticated){setAuth("register");return false;}setSavingWatch(true);try{await productRequest("/watchlist","PUT",{symbols});await refreshMe();notify("Watchlist saved to your account.");return true;}catch(e){notify(e instanceof Error ? e.message : "Could not save the watchlist.");return false;}finally{setSavingWatch(false);}}
  async function addWatch(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const input=String(new FormData(form).get("symbol")??"").trim().toUpperCase();if(!input)return;if(await saveWatch([...new Set([...(me?.watchlist??[]),normalizeMarketSymbol(input)])]))form.reset();}
  function marketRows(data:ScannerRow[]){return <div className="sw-market-table"><div className="sw-market-table-head"><span>Market / setup</span><span>Price / 24h</span><span>Heuristic score</span><span>Status</span><span /></div>{data.map(row=><div className="sw-market-row" key={row.symbol}><button className="sw-market-name" onClick={()=>me?.entitlements.scanner?void openSetup(row.symbol):upgrade()}><span className={`sw-coin ${displaySymbol(row.symbol).toLowerCase()}`}>{displaySymbol(row.symbol).slice(0,1)}</span><span><strong>{displaySymbol(row.symbol)} <small>/ USD</small></strong><span>{row.setup.replace(/([a-z])([A-Z])/g,"$1 $2")}</span></span></button><div className="sw-market-price"><strong>{money(row.price)}</strong><span className={(row.r24h??0)>=0?"positive":"negative"}>{row.r24h==null?"Change unavailable":`${row.r24h>=0?"+":""}${(row.r24h*100).toFixed(2)}%`}</span></div><div className="sw-market-score"><strong>{row.score}<span>/100</span></strong><span className="sw-score-track"><i style={{width:`${Math.max(0,Math.min(100,row.score))}%`}}/></span></div><div className="sw-market-status"><StatusPill tone={row.stale||row.doNotChase?"amber":"neutral"}>{row.stale?"Stale":row.doNotChase?"Do not chase":row.executionStatus==="Blocked"?"Checks blocked":row.executionStatus==="Watch"?"Conditional setup":"Observe"}</StatusPill></div><button className="sw-icon-button" aria-label={`Open ${row.symbol} setup`} onClick={()=>me?.entitlements.scanner?void openSetup(row.symbol):upgrade()}><Icon name="chevron" size={17}/></button></div>)}</div>;}
  const heading=headings[tab];
  return <div className="sw sw-app"><a href="#app-main" className="sw-skip">Skip to content</a><aside className="sw-sidebar"><Brand/><div className="sw-workspace-label">YOUR WORKSPACE</div><nav aria-label="Workspace">{navigation.map(n=><button key={n.tab} className={tab===n.tab?"active":""} aria-current={tab===n.tab?"page":undefined} onClick={()=>navigate(n.tab)}><Icon name={n.icon}/><span>{n.label}</span>{n.tab==="scanner"&&<span className="sw-nav-pro">PRO</span>}</button>)}</nav><div className="sw-sidebar-bottom"><div className="sw-side-upgrade"><span className="sw-label">A LITTLE MORE FREEDOM</span><h3>Your rules.<br/>Your rhythm.</h3><p>Monitor in the background with Pro.</p><button className="sw-text-link" onClick={upgrade}>Explore Pro <Icon name="arrow" size={16}/></button></div><button className="sw-profile" onClick={()=>me?.authenticated?navigate("account"):setAuth("login")}><span>{me?.user?.displayName?.[0]?.toUpperCase()??"G"}</span><span><strong>{me?.user?.displayName??"Guest workspace"}</strong><small>{me?.subscription.plan??"Free"} plan</small></span><Icon name="chevron" size={16}/></button></div></aside>
    <div className="sw-app-content"><header className="sw-app-header"><div className="sw-mobile-brand"><Brand/></div><div className="sw-breadcrumb">Workspace <Icon name="chevron" size={13}/> <span>{navigation.find(n=>n.tab===tab)?.label}</span></div><div className="sw-header-actions"><StatusPill tone={isLive?"green":"amber"}>{!online?"Offline":isLive?"Market feed connected":loading?"Connecting":overview?.mode==="disconnected"?"Feed disconnected":"Development preview"}</StatusPill>{!me?.authenticated&&<button className="sw-button secondary small" onClick={()=>setAuth("login")}>Sign in</button>}<button className="sw-icon-button sw-header-bell" onClick={()=>navigate("alerts")} aria-label="Open alerts"><Icon name="alerts"/></button></div></header>
      <main id="app-main" className="sw-app-main"><div className="sw-page-heading"><div><span className="sw-kicker">{heading.eyebrow}</span><h1>{heading.title}</h1><p>{heading.description}</p></div>{tab==="home"&&<button className="sw-button secondary" onClick={()=>navigate("scanner")}>Explore scanner <Icon name="arrow" size={17}/></button>}</div>
      {!online&&<div className="sw-notice error" role="status"><Icon name="info" size={18}/><span>You’re offline. Shown data may be outdated. Reconnect to refresh markets or save changes.</span></div>}
      {(error||scannerError||stale)&&<div className="sw-notice error" role="alert"><Icon name="info" size={18}/><span>{error||scannerError||"This snapshot is over 30 seconds old or has an invalid timestamp."} Previously loaded values may be stale.</span><button className="sw-text-link" disabled={refreshing} onClick={()=>void refreshOverview()}>Retry</button></div>}
      {sessionError&&<div className="sw-notice" role="status"><Icon name="info" size={18}/><span>Account service unavailable. You can explore the preview; account changes require a connection to the server.</span><button className="sw-text-link" onClick={()=>void refreshMe()}>Retry</button></div>}
      {tab!=="account"&&overview?.mode!=="live"&&!loading&&<div className="sw-preview-notice"><Icon name="info" size={17}/><p><strong>A considered preview.</strong> {overview?.reason??"Live market data is not connected in this preview."} Examples are illustrative and never issue alerts.</p></div>}
      {tab==="home"&&<>
        <section className="sw-home-stats" aria-label="Market status"><div><span className="sw-label">MARKET CONTEXT</span><div><strong>{isLive?(overview?.market?.regime.replace(/([a-z])([A-Z])/g,"$1 $2")??"Warming up"):"Awaiting live data"}</strong><Icon name="waves"/></div><small>{isLive?`${overview?.feed.exchange} · Spot USD`:"The quieter view starts here"}</small></div><div><span className="sw-label">ON YOUR WATCHLIST</span><div><strong>{me?.watchlist.length??0}<span> coins</span></strong><Icon name="watch"/></div><button className="sw-text-link" onClick={()=>navigate("watchlist")}>Choose what to follow <Icon name="arrow" size={13}/></button></div><div><span className="sw-label">QUALIFYING SETUPS</span><div><strong>{isLive?qualifying.length:"—"}<span>{isLive?" to inspect":""}</span></strong><Icon name="scan"/></div><small>{isLive?`Snapshot ${timeAgo(scanner?.at??overview?.at)}`:"No live setup claims in preview"}</small></div></section>
        <div className="sw-home-columns"><section className="sw-card sw-focus-card"><div className="sw-section-heading"><div><span className="sw-label">A CLOSER LOOK</span><h2>{isLive?"Conditions worth understanding":"An alert with a little more context."}</h2></div><StatusPill tone={isLive?"green":"amber"}>{isLive?"Engine analysis":"Example only"}</StatusPill></div>{loading?<div className="sw-loading" role="status">Connecting to the market service…</div>:isLive&&qualifying.length?marketRows(qualifying.slice(0,3)):isLive?<EmptyState title="Nothing qualifies right now.">The engine is waiting for market conditions, history, and risk checks to align. Criteria are never lowered to fill the screen.</EmptyState>:<><div className="sw-example-market"><div className="sw-coin-row"><span className="sw-coin btc">₿</span><div><strong>Bitcoin</strong><span>BTC / USD · Illustrative analysis</span></div></div><span className="sw-caption">NOT LIVE MARKET DATA</span></div><ExampleChart/><div className="sw-example-explanation"><div><h3>Near a key level. Waiting for confirmation.</h3><p>See the evidence, the conditions, and what would invalidate the idea.</p></div><button className="sw-button secondary small" onClick={openExample}>Read example <Icon name="arrow" size={16}/></button></div></>}</section><aside className="sw-home-aside"><section className="sw-card sw-get-started"><span className="sw-kicker">YOUR NEXT SMALL STEP</span><h2>Set your focus.<br/>Find your rhythm.</h2><p>{me?.authenticated?"Choose your coins and tailor monitoring around your schedule.":"Create an account to bring your watchlist and preferences together."}</p><button className="sw-button primary" onClick={()=>me?.authenticated?navigate(me.preferences?.onboardingComplete?"watchlist":"account"):setAuth("register")}>{me?.authenticated?"Personalize your workspace":"Make it yours"}<Icon name="arrow" size={17}/></button><div className="sw-check-line"><Icon name="check" size={14}/>No exchange credentials required</div></section><section className="sw-card sw-recent"><div className="sw-section-heading"><h3>Recent alerts</h3><Icon name="clock" size={18}/></div>{recent.length?recent.map(a=><button key={a.id} onClick={()=>navigate("alerts")} className="sw-recent-alert"><strong>{a.ruleName}</strong><span>{a.symbol} · {timeAgo(a.issuedAt)}</span></button>):<p>Your first alert will appear here. No examples are counted as real alerts.</p>}<button className="sw-text-link" onClick={()=>navigate("alerts")}>Go to alerts <Icon name="arrow" size={16}/></button></section></aside></div>
        <div className="sw-home-footer"><Icon name="shield" size={18}/><span>Built for perspective. Scores are heuristics, setups are conditional, and every decision stays yours.</span><a href="/legal#risk">Our approach <Icon name="arrow" size={15}/></a></div>
      </>}
      {tab==="scanner"&&<><div className="sw-scanner-toolbar"><label className="sw-search"><Icon name="search" size={18}/><input aria-label="Search markets" placeholder="Search a market, e.g. BTC" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="Clear search" onClick={()=>setQuery("")}><Icon name="close" size={15}/></button>}</label><div className="sw-filter-tabs" aria-label="Market filters">{[{value:"all",label:"All markets"},{value:"fresh",label:"Fresh data"},{value:"watching",label:"My watchlist"},{value:"breakout",label:"Breakouts"}].map(f=><button key={f.value} aria-pressed={filter===f.value} onClick={()=>setFilter(f.value)}>{f.label}</button>)}</div></div><section className="sw-card sw-scanner-card"><div className="sw-section-heading"><div><h2>{me?.entitlements.scanner?"Your full scanner":"Market overview"}</h2><p>{me?.entitlements.scanner?"Original engine criteria, with your costs applied.":"A limited overview. Pro unlocks the full scanner and setup details."}</p></div><button className="sw-icon-button" aria-label="Refresh market overview" disabled={refreshing} onClick={()=>void refreshOverview()}><Icon name="refresh" size={18}/></button></div>{loading?<div className="sw-loading" role="status">Checking the market feed…</div>:filtered.length?marketRows(filtered):<EmptyState title={query||filter!=="all"?"No markets match these filters.":isLive?"Nothing qualifies right now.":"The live scanner is waiting."} action={query||filter!=="all"?<button className="sw-button secondary small" onClick={()=>{setQuery("");setFilter("all");}}>Clear filters</button>:<button className="sw-button secondary small" onClick={openExample}>Explore an example <Icon name="arrow" size={16}/></button>}>{query||filter!=="all"?"Try a different symbol or clear your filters. Criteria stay the same.":overview?.reason??"When a permitted market feed is available, current market conditions will appear here. We never create signals to fill an empty screen."}</EmptyState>}</section>{!me?.entitlements.scanner&&<section className="sw-card sw-pro-banner"><span className="sw-feature-icon"><Icon name="scan" size={24}/></span><div><span className="sw-kicker">MORE CONTEXT. YOUR CONDITIONS.</span><h2>Make the full market your workspace.</h2><p>Pro adds the full scanner, detailed evidence, your fee assumptions, and background alert rules.</p></div><button className="sw-button primary" onClick={upgrade}>Explore Pro · $29/mo <Icon name="arrow" size={17}/></button></section>}<p className="sw-caption sw-scanner-footnote">Public listings do not confirm availability in your actual exchange account. Scores are not win probabilities. Price plans are conditional and may fail.</p></>}
      {tab==="watchlist"&&<section className="sw-card"><div className="sw-section-heading"><div><span className="sw-label">A SMALLER CORNER OF THE MARKET</span><h2>Your watchlist <span className="sw-count">{me?.watchlist.length??0}</span></h2></div><StatusPill>{me?.authenticated?`${me.watchlist.length} / ${me.entitlements.watchlistLimit} saved`:"Sign in to sync"}</StatusPill></div><form className="sw-watch-add" onSubmit={addWatch}><label className="sw-search"><Icon name="search" size={18}/><input name="symbol" aria-label="Market to add to watchlist" placeholder="Add a symbol, e.g. BTC or ETH/USD" required maxLength={30}/></label><button className="sw-button primary" disabled={savingWatch}><Icon name="plus" size={18}/>{savingWatch?"Saving…":"Add market"}</button></form>{me?.watchlist.length?<div className="sw-watch-list">{me.watchlist.map(symbol=>{const row=rows.find(r=>r.symbol===symbol);return <div key={symbol}><span className={`sw-coin ${displaySymbol(symbol).toLowerCase()}`}>{displaySymbol(symbol).slice(0,1)}</span><div><strong>{displaySymbol(symbol)} <span>/ USD</span></strong><small>{row?`${money(row.price)} · ${row.stale?"Stale data":row.setup}`:"Waiting for a qualifying analysis"}</small></div>{row&&<button className="sw-button secondary small" onClick={()=>me.entitlements.scanner?void openSetup(symbol):upgrade()}>View setup</button>}<button className="sw-icon-button" aria-label={`Remove ${symbol} from watchlist`} disabled={savingWatch} onClick={()=>void saveWatch(me.watchlist.filter(x=>x!==symbol))}><Icon name="close" size={17}/></button></div>;})}</div>:<EmptyState icon="watch" title="Your market starts with a few coins." action={<div className="sw-starter-coins">{["BTC","ETH","SOL"].map(c=><button className="sw-button secondary small" disabled={savingWatch} key={c} onClick={()=>void saveWatch([...(me?.watchlist??[]),normalizeMarketSymbol(c)])}><Icon name="plus" size={14}/>{c}</button>)}</div>}>Follow the markets that matter to you. Your saved list will sync when you sign in on another device.</EmptyState>}<p className="sw-caption">Use USD spot symbols. A saved symbol may have no current data or be unavailable in your exchange account or region.</p></section>}
      {tab==="alerts"&&<Alerts me={me} onUpgrade={upgrade} onMessage={notify} onOpenEvidence={opportunity=>setDetail({open:true,example:false,recorded:true,opportunity,loading:false,error:""})}/>}
      {tab==="account"&&<Account me={me} refresh={refreshMe} auth={setAuth} onMessage={notify}/>}
      </main><footer className="sw-app-footer"><span>Stillwatch · Development preview</span><div><a href="/legal#privacy">Privacy</a><a href="/legal#terms">Terms</a><a href="/legal#risk">Risk disclosure</a></div></footer>
    </div><nav className="sw-mobile-nav" aria-label="Mobile workspace">{navigation.map(n=><button key={n.tab} className={tab===n.tab?"active":""} aria-current={tab===n.tab?"page":undefined} onClick={()=>navigate(n.tab)}><Icon name={n.icon} size={20}/><span>{n.label}</span></button>)}</nav>
    {notice&&<div className="sw-toast" role="status"><Icon name="info" size={18}/><span>{notice}</span><button className="sw-icon-button" aria-label="Dismiss message" onClick={()=>setNotice("")}><Icon name="close" size={16}/></button></div>}
    {auth&&<Auth initialMode={auth} onClose={closeAuth} onSuccess={async()=>{await refreshMe();if(auth==="register"){closeAuth();navigate("account");notify("Account created. Choose your monitoring preferences below. Email verification requires configured delivery.");}}}/>}
    {detail.open&&<Setup opportunity={detail.opportunity} example={detail.example} recorded={detail.recorded} loading={detail.loading} error={detail.error} onClose={closeDetail}/>}
  </div>;
}
