"use client";
import { useCallback } from "react";
import type { Opportunity } from "@/lib/types";
import { ExampleChart, Icon, money, StatusPill } from "./Primitives";
import { Modal } from "./Modal";
export function Setup({ opportunity, example = false, recorded = false, loading, error, onClose }: { opportunity: Opportunity | null; example?: boolean; recorded?: boolean; loading?: boolean; error?: string; onClose: () => void }) {
  const close=useCallback(onClose,[onClose]);
  const symbol = example ? "Bitcoin · BTC / USD" : opportunity?.symbol.value ?? "Setup details";
  return <Modal title={symbol} onClose={close} wide>
    {loading ? <div className="sw-loading" role="status">Loading the engine’s analysis…</div> : error ? <div className="sw-notice error" role="alert">{error}</div> : example ? <>
      <StatusPill tone="amber">Illustrative example · not live market data</StatusPill><h3 className="sw-setup-headline">A level worth watching. A reason to wait.</h3><p className="sw-form-intro">This fictional example shows how a setup is explained. It is not a current alert, a historical result, or a trade recommendation.</p><ExampleChart /><div className="sw-setup-grid"><section><span className="sw-label">OBSERVED FACTS · EXAMPLE</span><h3>Price approaches resistance</h3><p>In this example, price is near a previously tested level while recent volume is above its local baseline.</p></section><section><span className="sw-label">CONDITIONAL SETUP · EXAMPLE</span><h3>Confirmation comes first</h3><p>Monitor for a sustained break and retest with supportive volume. Reassess if price returns below the level or market context weakens.</p></section><section><span className="sw-label">HEURISTIC, NOT PROBABILITY</span><h3>Evidence you can inspect</h3><p>Real analyses preserve the existing engine’s score components and criteria. Scores are not a probability of profit.</p></section><section><span className="sw-label">COSTS CHANGE THE PICTURE</span><h3>Your fees belong in the plan</h3><p>Real Pro analyses use your configured fee and slippage assumptions. Net risk and reward can differ substantially from headline price levels.</p></section></div><div className="sw-notice"><Icon name="info" size={18}/><span>Example only. No outcome was recorded and no market event occurred from this illustration.</span></div>
    </> : opportunity ? <>
      <div className="sw-setup-status"><StatusPill tone={opportunity.quality.stale ? "amber" : "green"}>{opportunity.quality.stale ? "Stale · do not act on this snapshot" : recorded ? "Recorded at alert issuance" : "Engine snapshot"}</StatusPill><span className="sw-caption">{new Date(opportunity.at).toLocaleString()}</span></div><h3 className="sw-setup-headline">{opportunity.setup.type.replace(/([a-z])([A-Z])/g,"$1 $2")}</h3><p className="sw-form-intro">{opportunity.why[0] ?? "Inspect the conditions and price levels before making any decision."}</p><div className="sw-setup-stats"><div><span>Observed price</span><strong>{money(opportunity.price)}</strong></div><div><span>Heuristic score</span><strong>{opportunity.score}<small> / 100</small></strong></div><div><span>Data age at analysis</span><strong>{(opportunity.quality.ageMs/1000).toFixed(1)}<small> sec</small></strong></div></div>
      <div className="sw-setup-grid"><section><span className="sw-label">WHAT HAPPENED</span><h3>Observed evidence</h3><ul>{opportunity.why.map((x,i)=><li key={i}>{x}</li>)}</ul><p className="sw-caption">{opportunity.quality.exchange} · {opportunity.quality.provider} · History {opportunity.quality.historyLoaded ? "loaded" : "still warming up"}</p></section><section><span className="sw-label">WHY IT MATCHED</span><h3>Conditional interpretation</h3><ul>{opportunity.setup.evidence.map((x,i)=><li key={i}>{x}</li>)}</ul><p className="sw-caption">{opportunity.setup.confidence} heuristic confidence · {opportunity.setup.bias} bias. These are descriptive labels, not estimated win probabilities.</p></section></div>
      {opportunity.plan ? <section className="sw-setup-levels"><span className="sw-label">CONDITIONAL PRICE LEVELS</span><h3>{opportunity.plan.trigger}</h3><dl><div><dt>Entry zone</dt><dd>{money(opportunity.plan.entryLow)} – {money(opportunity.plan.entryHigh)}</dd></div><div><dt>Invalidation</dt><dd>{money(opportunity.plan.invalidation)}</dd></div><div><dt>Stop reference</dt><dd>{money(opportunity.plan.stop)}</dd></div><div><dt>First target</dt><dd>{money(opportunity.plan.target1)}</dd></div><div><dt>Chase ceiling</dt><dd>{money(opportunity.plan.chaseCeiling)}</dd></div><div><dt>Net reward / risk</dt><dd>{opportunity.execution?.netRewardRatio?.toFixed(2) ?? "Unavailable"}</dd></div></dl><p className="sw-caption">Conditional references, not orders. Stops can slip and losses may exceed estimates. Entry state: {opportunity.plan.entryState}.</p></section> : <div className="sw-notice">No actionable price plan qualifies under the engine’s current criteria.</div>}
      <div className="sw-setup-grid"><section><span className="sw-label">WHEN THE IDEA NO LONGER HOLDS</span><h3>Invalidation & risks</h3><p>{opportunity.invalidation}</p><ul>{opportunity.risks.map((r,i)=><li key={i}>{r}</li>)}{opportunity.overextension.flags.map((r,i)=><li key={`o${i}`}>{r}</li>)}</ul></section><section><span className="sw-label">ESTIMATED TRADING COSTS</span><h3>After your assumptions</h3><p>Fee: {opportunity.execution?.feeBps ?? "unavailable"} bps / side. Slippage: {opportunity.execution?.slippageBps ?? "unavailable"} bps / side.</p><p>Estimated entry cost per unit: {money(opportunity.execution?.entryCostPerUnit)}.</p><ul>{opportunity.execution?.reasons.map((r,i)=><li key={i}>{r}</li>)}</ul><p className="sw-caption">Estimates are not actual fills. Fees, spread, liquidity and slippage may change.</p></section></div>
      <details className="sw-advanced"><summary>Advanced score components <Icon name="plus" size={17}/></summary>{opportunity.breakdown.components.map((c,i)=><div key={i} className="sw-breakdown"><div><strong>{c.name}</strong><span>{c.points} / {c.max}</span></div><p>{c.evidence}</p></div>)}{opportunity.breakdown.penalties.map((c,i)=><div key={i} className="sw-breakdown"><div><strong>{c.name}</strong><span>{c.points}</span></div><p>{c.evidence}</p></div>)}</details><p className="sw-caption">{recorded ? "This is the immutable evidence saved when the alert was issued, not current market conditions." : "Snapshot analysis can become outdated. Recheck the market before acting."} Heuristic analysis is not investment advice.</p>
    </> : null}
  </Modal>;
}
