import { Brand } from "@/components/product/Primitives";

export default function LegalPage() {
  return <div className="sw" style={{ minHeight: "100vh" }}><header className="sw-site-header sw-container"><Brand /><a className="sw-button secondary small" href="/app/">Open app</a></header>
    <main className="sw-container" style={{ maxWidth: 900, paddingTop: 48, paddingBottom: 90 }}>
      <p className="sw-kicker">REVIEW DRAFTS · SEPTEMBER 12, 2026</p><h1 style={{ fontSize: "clamp(32px, 6vw, 56px)", lineHeight: 1.1 }}>Clear about the details.</h1>
      <p className="sw-notice" role="note">These documents need business and legal review before a public paid launch. Operator name, address, support contact and governing jurisdiction are unresolved. This preview does not establish that the product is approved for your jurisdiction.</p>
      <nav aria-label="Legal documents" className="sw-legal-links"><a href="#privacy">Privacy draft</a><a href="#terms">Terms draft</a><a href="#risk">Risk disclosure</a></nav>
      <section id="privacy" className="sw-card" style={{ marginTop: 32, lineHeight: 1.85 }}><h2>Privacy notice — draft</h2>
        <p><strong>Operator:</strong> [LEGAL BUSINESS NAME, ADDRESS AND PRIVACY CONTACT REQUIRED].</p>
        <p>Stillwatch stores your email, display name, securely hashed password, monitoring preferences, watchlist, alert rules, notification-device subscriptions, alert evidence, delivery diagnostics and support requests. Session and security cookies keep your account signed in and protect account actions.</p>
        <p>We use this information to provide your workspace, sync preferences, evaluate rules, send notifications you enable, manage access and investigate service problems. We do not request exchange passwords, trading keys or withdrawal permission.</p>
        <p>Hosted checkout uses the payment provider. The app retains customer/subscription identifiers and payment status, rather than full card details. A configured mail provider handles account messages; browser push providers process notification payloads and device subscription identifiers. [FINAL PROCESSORS, HOSTING REGIONS, TRANSFER ARRANGEMENTS AND LEGAL BASES REQUIRE REVIEW].</p>
        <p>Account deletion is available in Account and removes owned application data after active subscription cancellation is confirmed. Payment-provider records and backups may have separate retention requirements. [CONFIRM RETENTION PERIODS, BACKUP ERASURE, LEGAL EXCEPTIONS AND PRIVACY REQUEST PROCESS]. History access has a configured window; this is not a claim that every backup is erased on that date.</p>
        <p>You can change preferences, turn off push, remove devices and delete your account. Contact [PRIVACY CONTACT REQUIRED] for unresolved access, correction, export or deletion requests. We do not claim a completed privacy compliance review. This preview uses no advertising-tracking integration.</p>
      </section>
      <section id="terms" className="sw-card" style={{ marginTop: 24, lineHeight: 1.85 }}><h2>Terms of service — draft</h2>
        <p><strong>Contracting business and jurisdiction:</strong> [LEGAL ENTITY, ADDRESS, ELIGIBILITY, GOVERNING LAW AND DISPUTE PROCESS REQUIRED].</p>
        <p>Stillwatch provides crypto market monitoring and conditional setup information. You are responsible for deciding whether an asset is available in your actual exchange account and for assessing any action you take. The product does not custody assets, execute trades or provide guaranteed outcomes.</p>
        <p>The Free plan provides a limited overview, labeled example analyses and starter preferences/watchlist. Pro is proposed at US $29 per month with a full scanner, configurable watchlists and rules, supported push notifications, detailed setup explanations and saved alert history. Current limits appear in Account. [TAX TREATMENT, RENEWAL DISCLOSURES AND REFUND POLICY REQUIRE REVIEW].</p>
        <p>This development release supports test checkout only. Live charging is disabled. Production terms, billing authorization and commercial permissions must be completed before accepting real subscription payments. Paid access depends on verified payment-provider state, not a checkout return page.</p>
        <p>Use Account to manage or cancel a configured subscription. Access normally continues to the verified paid period end when cancellation is scheduled; failed, expired or canceled subscriptions can lose Pro access. Final cancellation, refund and consumer rights language must match the approved launch jurisdiction and provider setup.</p>
        <p>Keep your password secure and do not attempt to access another customer’s data. Service interruptions, stale exchange feeds, device settings and third-party outages can prevent alerts. [SUPPORT CONTACT, SERVICE COMMITMENTS, LIABILITY TERMS AND CHANGE-NOTICE PROCESS REQUIRE REVIEW].</p>
      </section>
      <section id="risk" className="sw-card" style={{ marginTop: 24, lineHeight: 1.85 }}><h2>Risk disclosure — review draft</h2>
        <p>Crypto markets can be volatile and illiquid. You can lose the amount you trade. Fees, spread and slippage can make a seemingly attractive setup uneconomic. Public prices and listings do not confirm a fill, account eligibility or your actual fee tier.</p>
        <ul><li><strong>Observed facts</strong> are timestamped data received from a source and may be delayed or incomplete.</li><li><strong>Heuristic scores</strong> summarize engine criteria. They are not calibrated win probabilities.</li><li><strong>Conditional setups</strong> describe a scenario, confirmation trigger and invalidation. They can fail.</li><li><strong>Illustrative examples</strong> show the product’s behavior using invented demonstration values and are labeled accordingly.</li><li><strong>Simulated or quote-observed outcomes</strong> do not prove executable fills. Quote sampling can miss price movement between observations; fees and slippage are estimates.</li><li><strong>Actual recorded trades</strong> would require real execution evidence. This monitoring release records no customer executions.</li></ul>
        <p>Alerts retain the evidence known at issue time. Later observations do not rewrite that evidence. Unfavorable and favorable observations are retained under the same policy. Past or simulated outcomes do not promise future performance.</p>
        <p>Push delivery is best effort and can be delayed or unavailable. Installation, permission, device/network conditions and supported software are necessary. Always check the current data and setup before making your own decision.</p>
      </section>
      <p className="sw-caption" style={{ marginTop: 28 }}>Need help in this development preview? <a href="/app/?tab=account">Open Account and support.</a> Business contact details remain to be supplied.</p>
    </main></div>;
}
